// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConsoleLog(arg1:string):Promise<void>;

export function CreateTerminal(arg1:main.TerminalConfig):Promise<number>;

export function GetDetails(arg1:number):Promise<string>;
