// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConsoleLog(arg1) {
  return window['go']['main']['App']['ConsoleLog'](arg1);
}

export function CreateTerminal(arg1) {
  return window['go']['main']['App']['CreateTerminal'](arg1);
}

export function ExitWithErr(arg1) {
  return window['go']['main']['App']['ExitWithErr'](arg1);
}

export function GetDetails(arg1) {
  return window['go']['main']['App']['GetDetails'](arg1);
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function ReadConfigFile() {
  return window['go']['main']['App']['ReadConfigFile']();
}
